name: upqayt
description: "An application that facilitates ordering food and groceries from restaurants and cafes"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  retrofit: ^4.4.2
  json_annotation: ^4.9.0
  logger:
  flutter_bloc: ^9.0.0
  get:
  freezed_annotation:
  equatable:
  hydrated_bloc: ^10.0.0
  replay_bloc: ^0.3.0
  bloc_concurrency:
  shared_preferences:
  flutter_secure_storage: ^9.2.4
  flutter_device_name: ^0.0.2
  mockito: ^5.4.5
  riverpod:
  flutter_riverpod:
  get_it: ^8.0.3
  bloc_test:
#  flutter_form_bloc:
  flutter_hooks:
  flutter_svg: ^2.0.17
  yandex_mapkit: ^4.1.0
#  yandex_mapkit_community: ^3.2.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  flutter_screenutil: ^5.9.3
  contained_tab_bar_view: ^0.8.0
  buttons_tabbar: ^1.3.15
  sms_autofill: ^2.4.1
  otp_text_field_v2: ^1.0.3
  dio: ^5.7.0
  http:
  jwt_io: ^1.1.6
  google_fonts: ^6.2.1
  intl: 
  persistent_bottom_nav_bar_v2: ^5.3.1
  flutter_styled_toast:
  flutter_local_notifications:
#  firebase_messaging:
  firebase_core: ^3.10.1
  firebase_crashlytics: ^4.3.1
  camera: ^0.11.1
  path_provider: ^2.1.5
  loading_animation_widget: ^1.3.0
  animated_bottom_navigation_bar: ^1.3.3
  add_to_cart_animation: ^2.0.4
  animations: ^2.0.11
  flutter_map_animations: ^0.8.0
  marquee: ^2.3.0
  marquee_list: ^1.0.0
  shimmer: ^3.0.0
  shimmer_animation: ^2.2.2
  searchbar_animation: ^0.0.4
  bottom_sheet: ^4.0.4
  interactive_bottom_sheet: ^1.0.0
  flutter_network_connectivity: ^0.0.6
  connectivity_plus: ^6.1.1
  flutter_statusbarcolor_ns: ^0.6.0
  syncfusion_flutter_sliders: ^28.1.41
  device_info_plus: ^11.2.0
  google_sign_in: ^6.2.2
#  sign_in_with_apple: ^5.0.0
  pull_to_refresh_flutter3: ^2.0.2
  fuzzy: ^0.5.1
  material_floating_search_bar_2: ^0.5.0
  flutter_rating_bar: ^4.0.1
  flutter_search_bar: ^3.0.0
  lazy_load_scrollview: ^1.3.0
  filter_list: ^1.0.3
  flutter_libphonenumber:
  flutter_face_api: ^6.4.875
  flutter_document_reader_api: ^7.5.1093
  flutter_document_reader_core_fullrfid: ^7.5.887
#  google_generative_ai: ^0.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.3
  build_runner: ^2.4.14
  retrofit_generator: ^9.1.7
  freezed:
  analyzer:
  flutter_launcher_icons: ^0.14.3

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "path/to/image.png"
flutter:

  uses-material-design: true

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/static/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik/static/Rubik-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Rubik/static/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik/static/Rubik-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Rubik/static/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik/static/Rubik-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Rubik/static/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik/static/Rubik-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Rubik/static/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik/static/Rubik-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Rubik/static/Rubik-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Rubik/static/Rubik-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Rubik/static/Rubik-Black.ttf
          weight: 900
        - asset: assets/fonts/Rubik/static/Rubik-BlackItalic.ttf
          weight: 900
          style: italic

  assets:
    - assets/
    - assets/l10n/
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/fonts/Rubik/
    - assets/fonts/Rubik/static/
    - assets/mock_data/

